# ****DISTRIBUTION PROHIBITED**

## **Basic linear algebra**

#### 1. Scalar
- $x \in R$
- value
- no direction; only magnitude
- rank 0

#### 2. Vector
- $\boldsymbol{x}\in R^p$
- set of values
- direction & magnitude
- dimensionality
- rank 1

#### 3. Matrix
- $\boldsymbol{X} \in R^{n\times p}$
- set of vectors (row-wise, column-wise)
- rank 2

#### e.g.) $\boldsymbol{Ax=b}$
$\begin{bmatrix}
  1 & 1\\
  4 & 2 \\
\end{bmatrix} \begin{bmatrix}
x_1 \\
x_2
\end{bmatrix}= \begin{bmatrix}
8 \\
26 \\
\end{bmatrix}$

#### 4. Basic Arithmetic
- Addition
- Multiplication
 - Matrix multiplication (@ in Numpy)
 - Hadamard (component-wise) multiplication (* in Numpy)

#### 5. Matrix Operation
- Rearrange (e.g., reshape, transpose)
- Concatenate

#### 6. Decomposition
- Eigenvalue decomposition: $A=Q\Lambda Q^{-1} $, given $A \in R^{m \times m}$
- Singular value decomposition: $A=U\Sigma V^T $ given $A \in R^{m \times n}$



In [ ]:
import numpy as np

In [ ]:
# scalar

a = np.array(3)
print('Value: ',a)
print('Shape: ',a.shape)

Value:  3
Shape:  ()


In [ ]:
a_1 = np.array([3])
print('Value: ',a_1)
print('Shape: ',a_1.shape)

Value:  [3]
Shape:  (1,)


In [ ]:
# vector

vec = np.array([1,2,3])
print('Value: ',vec)
print('Shape: ',vec.shape)

Value:  [1 2 3]
Shape:  (3,)


In [ ]:
# matrix

mat = np.array([[1,2],[4,5]]) # 2 x 2 square matrix
print('Value: ',mat)
print('Shape: ',mat.shape)

mat_1 = np.array([[1,2,3],[4,5,6]]) # 2 x 3 rectangular matrix
print('Value: ',mat_1)
print('Shape: ',mat_1.shape)

Value:  [[1 2]
 [4 5]]
Shape:  (2, 2)
Value:  [[1 2 3]
 [4 5 6]]
Shape:  (2, 3)


#### 4. Basic Arithmetic
- Addition
- Multiplication
 - Matrix multiplication
 - Hadamard (component-wise) multiplication

In [ ]:
vec_1 = np.array([1,2,3])
vec_2 = np.array([4,5,6])

print(vec_1+vec_2)

print(vec_1*vec_2)
print(np.matmul(vec_1,vec_2))

[5 7 9]
[ 4 10 18]
32


In [ ]:
a_1 = vec_1.reshape(3,1)
b_1 = vec_2.reshape(1,3)

print(a_1+b_1)
print(a_1*b_1)
print(np.matmul(a_1,b_1))

a_2 = vec_1.reshape(1,3)
b_2 = vec_2.reshape(3,1)

print(a_2+b_2)
print(a_2*b_2)
print(np.matmul(a_2,b_2))

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[ 4  8 12]
 [ 5 10 15]
 [ 6 12 18]]
[[32]]


#### 5. Matrix Operation
- Rearrange (e.g., reshape, transpose)
- Concatenate

In [ ]:
# Rearrange

a = np.array(20) # scalar
print('Scalar shape: ',a.shape)
a_1 = a.reshape(-1,1) # column-dependent
print('Transformed scalar shape: ',a_1.shape)

vec = np.linspace(-1,1,100) # vector
print('Vector shape: ',vec.shape)
vec_1 = vec.reshape(-1,5) # column-dependent
print('Transformed vector shape: ',vec_1.shape)
vec_2 = vec.reshape(20,-1) # row-dependent
print('Transformed vector shape: ',vec_2.shape)

mat = np.random.normal(size=(5,2)) # matrix
print('Matrix shape: ',mat.shape)
mat_1 = mat.T # transpose
print('Transformed matrix shape: ',mat_1.shape)
mat_2 = mat.transpose() # transpose
print('Transformed matrix shape: ',mat_2.shape)

Scalar shape:  ()
Transformed scalar shape:  (1, 1)
Vector shape:  (100,)
Transformed vector shape:  (20, 5)
Transformed vector shape:  (20, 5)
Matrix shape:  (5, 2)
Transformed matrix shape:  (2, 5)
Transformed matrix shape:  (2, 5)


In [ ]:
# Concatenate

# square matrix
vec_1 = np.array([1,2,3])
vec_2 = np.array([4,5,6])
vec_3 = np.array([7,8,9])

## rectangular matrix
# vec_1 = np.array([1,2])
# vec_2 = np.array([4,5])
# vec_3 = np.array([7,8])

con_1 = np.concatenate((vec_1,vec_2,vec_3))
print(con_1)
con_2 = np.concatenate((vec_1,vec_2,vec_3),axis=-1)
print(con_2)

con_3 = np.concatenate((vec_1.reshape(-1,1),vec_2.reshape(-1,1),vec_3.reshape(-1,1)))
print(con_3)
con_4 = np.concatenate((vec_1.reshape(-1,1),vec_2.reshape(-1,1),vec_3.reshape(-1,1)),axis=-1)
print(con_4)
print(con_4.T)

[1 2 4 5 7 8]
[1 2 4 5 7 8]
[[1]
 [2]
 [4]
 [5]
 [7]
 [8]]
[[1 4 7]
 [2 5 8]]
[[1 2]
 [4 5]
 [7 8]]


## Q1:

Three integers randomly extracted between 0 and 6 are used as a vector, three values that follow the standard normal distribution are randomly extracted as another vector, and the two are concatenated in the column direction to form a matrix. Two values that follow a uniform distribution between 2 and 3 are extracted as one vector, and two values that follow a normal distribution with a mean of 1 and a standard deviation of 3 are extracted as another vector. In a situation where two integers are randomly extracted between 1 and 10 and made into another vector, each vector is transposed and concatenated in the row direction to make another matrix, and then transposed and then perform the multiplication operation of the two matrices.

0과 6 사이에서 3개의 integer 랜덤하게 추출한 것을 벡터로, 표준정규분포를 따르는 3개의 값을 랜덤하게 추출한 것을 또 하나의 벡터로 하고 이 둘을 열 방향으로 이어 붙인 것을 하나의 행렬로, 2와 3 사이에서 uniform distribution을 따르는 2개의 값을 추출한 것을 한 벡터로, 평균 1, 표준편차 3으로 정규분포를 따르는 2개의 값을 추출한 것을 또 하나의 벡터로, 1과 10 사이에서 2개의 integer를 랜덤으로 추출한 것을 또 하나의 벡터로 만든 상황에서 각 벡터를 transpose 한 후 행 방향으로 이어 붙인 것을 또 하나의 행렬로 만든 후 transpose 한 뒤 두 행렬 곱셈 연산을 수행하라.


#### 6. Decomposition
- Eigenvalue decomposition: $A=Q\Lambda Q^{-1} $, given $A \in R^{m \times m}$
- Singular value decomposition: $A=U\Sigma V^T $ given $A \in R^{m \times n}$



In [ ]:
# Eigenvalue decomposition

mat = np.array([ [2,1,3], [0,1,1], [1,2,1] ])
print(mat)

lam, U = np.linalg.eig(mat) # eigenvalue and eigenvectors

print(lam)
print(U)

lam_mat = np.diag(lam)
U_inv = np.linalg.inv(U)

# mat_recon = np.dot(U,np.dot(lam_mat,U_inv)) # taking the product of our three matrices
mat_recon = U@lam_mat@U_inv # another version

def round(values, decs=0): # we don't want to include decimal points in our returned matrix
  return np.round(values*10**decs)/(10**decs)

mat_recon = round(mat_recon, decs=0)

print(mat_recon)

[[2 1 3]
 [0 1 1]
 [1 2 1]]
[ 3.70927536 -0.90321193  1.19393657]
[[ 0.87961308  0.60231797  0.88755164]
 [ 0.16471621  0.37129341 -0.45228128]
 [ 0.44626158 -0.70665004 -0.08771388]]
[[ 2.  1.  3.]
 [-0.  1.  1.]
 [ 1.  2.  1.]]


In [ ]:
# Singular value decomposition

np.random.seed(121)
mat = np.random.randn(3,4)
print(np.round(mat, 3))

U,S,V_t = np.linalg.svd(mat)

print(U.shape)
print(V_t.shape)
print(S.shape)
print(np.diag(S).shape)

S_new = np.c_[np.diag(S), np.zeros(mat.shape[0])]
print(S_new.shape)

mat_recon = U@S_new@V_t
print(round(mat_recon, decs=3))

[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]]
(3, 3)
(4, 4)
(3,)
(3, 3)
(3, 4)
[[-0.212 -0.285 -0.574 -0.44 ]
 [-0.33   1.184  1.615  0.367]
 [-0.014  0.63   1.71  -1.327]]
